### ISSUE TITLE
Kill foreground app not working

### ISSUE THREAD

**Issue by papypaprika** [DrAcHe981/NeoPowerMenu#28]
Hello,

The Kill Foreground App shortcut doesn't work for me, I'm on Nougat 7.0, rooted with Magisk, Xposed 88.2, on a Samsung Galaxy A5 (2016).

Is it because this needs a busybox to be installed, which I don't have, or because it uses dumpsys which Magisk doesn't support?

Thanks !

**Comment by DrAcHe981** [comment]
Tested the command im using to kill an app in a ADB window and a not rooted device, since I have no 
 rooted device without busybox nor a magisk device, and even there it worked

Possible reason could be that there are invisible apps in front of the app you want to kill, that happens for example when the keyboard was active, or I experienced right now that the google service also is in front of other apps sometimes, but without visible ui

Please take a look in the xposed log and check if there is something among the lines of "`[NeoPowerMenu] Received broadcast: de.NeonSoft.neopowermenu.action.KillApp`", below that should be a message displaying which app it will try to kill, and if errors occurred they will also be there

**Comment by papypaprika** [comment]
Hi, thank you for your quick reply, after switching deep logging on, I see the following error:

[NeoPowerMenu] Received broadcast: de.NeonSoft.neopowermenu.action.KillApp
[NeoPowerMenu] Trying to kill de.robv.android.xposed.installer (10465)
[NeoPowerMenu] Aborting broadcast, to prevent multiple calls!

Any ideas?

**Comment by DrAcHe981** [comment]
Not much info in that log...

Anyways, reworked the entire function right now, please try this version!
[NeoPowerMenu_ReworkKillApp.apk (Download from Neon-Soft.de)](http://neon-soft.de/files/NeoPowerMenu_ReworkKillApp.apk)

It now uses either the activity manager class, or if that's not possible, it tries the Process class, both functions that should be available on every device!

(this compiled version also contains my recent changes, so some might be buggy...)

**Comment by papypaprika** [comment]
Bad luck, killing the foreground application with this version systematically kills System UI...

**Comment by DrAcHe981** [comment]
Okay, first off, let us continue this on the issue for it ^^

Second, I was indeed right, it crashed the system UI instead of killing it!
Reason for that is that the system UI apparently has no permission to force stop packages, which is kinda weird for a system app

I adjusted my scripts, the apk file is available as the [latest "unstable" release](https://github.com/DrAcHe981/NeoPowerMenu/releases/download/UNSTABLE_TravisCI_Release_01-02-2018_14-55-29_c60f1c6/NeoPowerMenu_TravisCI.apk)!
**Reboot needed for the changes to take effect!**

**Comment by papypaprika** [comment]
Great !! It works. Thank you so much for looking into this!


-------- Original message --------
