### ISSUE TITLE
Tasker shortcuts not working anymore since 1.5.6-9(56)

### ISSUE THREAD

**Issue by papypaprika** [DrAcHe981/NeoPowerMenu#45]
None of my Tasker shortcuts can be triggered from NeoPowerMenu, they are perfectly working on a standalone basis and were working in previous NeoPowerMenu versions. Any ideas?

**Comment by DrAcHe981** [comment]
Time to install tasker on my testing device again-

Will have to wait until today evening tho, I will report back after I did some tests!

**Comment by papypaprika** [comment]
Awesome thank you!
Also, the "Kill foreground application" still kills System UI rather than the foreground app, I don't know if you could look into it again?

**Comment by DrAcHe981** [comment]
Okay the shortcut issue was completely my fault...
I accidentally removed the entire script that was handling them, no idea when that happened tho...
Will be fixed in next release! (And its also already in the the latest ["unstable" release](https://github.com/DrAcHe981/NeoPowerMenu/releases/tag/UNSTABLE_TravisCI_Release_25-01-2018_17-45-10_6992e16) here on github)

To the ```Kill foreground app``` button issue: start a logcat task with ```adb logcat *:E -v long > crash.txt``` BEFORE tapping on the kill button, because i have the feeling its crashing the system ui instead of killing it.

**Comment by papypaprika** [comment]
Hi,
Thank you very much for looking into this.
See attached my logcat




-------- Original message --------

**Comment by DrAcHe981** [comment]
I think your attachment went missing in the GitHub servers (I get nothing about an attachment displayed in GitHub or google inbox)
I'm guessing GitHub does not support attachments in their email reply system...

Just send the logcat directly to my personal email address drache981@gmail.com and it should definitely reach me!

**Comment by papypaprika** [comment]
Weird. See attached. Thank you very much !




-------- Original message --------
